classes:
- service.galera.ssl
- service.galera.master.cluster
- system.galera.server.database.cinder
- system.galera.server.database.designate
- system.galera.server.database.glance
- system.galera.server.database.heat
- system.galera.server.database.keystone
- system.galera.server.database.nova
parameters:
  galera:
    master:
      ~members:
      - host: ${_param:single_address}
        port: 4567
      innodb_buffer_pool_size: 1024M
      max_connections: 1000
    slave:
      enabled: false
